// AUTO-GENERATED — do not edit. Source: tauri-specta in src-tauri/src/lib.rs.
// Regenerate via `pnpm gen` (or `cargo run --example export_bindings`).

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	dictateOnce: (style: Style) => typedError<DictateResult, BoothError>(__TAURI_INVOKE("dictate_once", { style })),
	/**
	 *  Update the active style. Called by the FE whenever the user changes the
	 *  dropdown; the session daemon reads `settings::current_style()` before
	 *  each LLM cleanup call.
	 */
	setDictationStyle: (style: Style) => __TAURI_INVOKE<void>("set_dictation_style", { style }),
	historyRecent: (limit: number | null) => typedError<HistoryEntry[], BoothError>(__TAURI_INVOKE("history_recent", { limit })),
	historySearch: (query: string, limit: number | null) => typedError<SearchResult[], BoothError>(__TAURI_INVOKE("history_search", { query, limit })),
	historyDelete: (id: number) => typedError<null, BoothError>(__TAURI_INVOKE("history_delete", { id })),
	historyClear: () => typedError<null, BoothError>(__TAURI_INVOKE("history_clear")),
	historyStats: () => typedError<HistoryStats, BoothError>(__TAURI_INVOKE("history_stats")),
	/**
	 *  Paste the formatted text of a history entry. Called from the main
	 *  settings UI; pastes wherever focus currently sits. For paste-back-into-
	 *  the-previously-focused-app behavior, use [`quickpaste_paste`] instead.
	 */
	historyPaste: (id: number) => typedError<HistoryPasteResult, BoothError>(__TAURI_INVOKE("history_paste", { id })),
	/**
	 *  Quick-paste palette flow: hide the palette, restore focus to the
	 *  previously-captured target window, then paste. Called by the palette
	 *  UI when the user picks an entry (Enter or click).
	 */
	quickpastePaste: (id: number) => typedError<HistoryPasteResult, BoothError>(__TAURI_INVOKE("quickpaste_paste", { id })),
	// Hide the quick-paste palette without pasting (e.g. user pressed Esc).
	quickpasteClose: () => typedError<null, BoothError>(__TAURI_INVOKE("quickpaste_close")),
	/**
	 *  Open the relevant Privacy & Security pane in System Settings. No-op on
	 *  non-macOS platforms (returns Ok). The OS handles the rest — once the
	 *  user toggles the relevant switch, the next dictation should work.
	 */
	openMacosSetting: (pane: MacPermissionPane) => typedError<null, BoothError>(__TAURI_INVOKE("open_macos_setting", { pane })),
	/**
	 *  Probe whether the OS is currently letting us read the default input
	 *  device. A `false` result means either the mic was denied at the TCC
	 *  layer or no input device is connected — both of which prevent
	 *  dictation. Cheap; safe to call on app start. Real-engines only since
	 *  the cpal probe lives behind that feature.
	 */
	microphoneAvailable: () => __TAURI_INVOKE<boolean>("microphone_available"),
	/**
	 *  Probe whether Screen Recording TCC is currently granted, without
	 *  triggering the OS prompt. Returns `true` on non-macOS (no-op) so
	 *  the FE doesn't need to branch — the OCR feature itself is gated
	 *  at runtime by the actual capture call.
	 */
	screenRecordingAvailable: () => __TAURI_INVOKE<boolean>("screen_recording_available"),
	/**
	 *  Eagerly request Screen Recording permission so the OS prompt
	 *  fires now (rather than the first time the cleanup pass tries an
	 *  OCR capture mid-dictation, which is the worst possible moment).
	 *  Returns whether access is granted afterwards. The OS prompt only
	 *  appears once per app per macOS reset; subsequent calls just
	 *  return the current state. Calls `CGRequestScreenCaptureAccess()`
	 *  which both prompts and registers the app in System Settings →
	 *  Privacy & Security → Screen Recording.
	 */
	requestScreenRecordingPermission: () => __TAURI_INVOKE<boolean>("request_screen_recording_permission"),
	/**
	 *  Report which Whisper model file the daemon will load (or already loaded).
	 *  The UI uses this to show "tiny.en" / "base.en" / "small.en" rather than a
	 *  hardcoded label, so the chip stays honest after the user swaps models via
	 *  `BOOTHRFLOW_WHISPER_MODEL_FILE`. Returns the file stem ("ggml-small.en").
	 */
	whisperModelName: () => __TAURI_INVOKE<string>("whisper_model_name"),
	settingsGet: () => typedError<AppSettings, BoothError>(__TAURI_INVOKE("settings_get")),
	settingsUpdate: (patch: SettingsPatch) => typedError<AppSettings, BoothError>(__TAURI_INVOKE("settings_update", { patch })),
	settingsOptions: () => __TAURI_INVOKE<SettingsOptions>("settings_options"),
	settingsExport: () => typedError<string, BoothError>(__TAURI_INVOKE("settings_export")),
	settingsImport: (json: string) => typedError<AppSettings, BoothError>(__TAURI_INVOKE("settings_import", { json })),
	whisperDownloadModel: (model: string) => typedError<WhisperDownloadResult, BoothError>(__TAURI_INVOKE("whisper_download_model", { model })),
	llmTestConnection: () => typedError<LlmTestResult, BoothError>(__TAURI_INVOKE("llm_test_connection")),
	// App version reported by the Cargo manifest. Used by the About section.
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	/**
	 *  Open a path (file or directory) in the OS file browser. Used by the
	 *  About section's "reveal in Finder" links — model dir, history db.
	 *  Falls through to `tauri-plugin-opener` so the same command works
	 *  across macOS / Windows / Linux.
	 */
	revealPath: (path: string) => typedError<null, BoothError>(__TAURI_INVOKE("reveal_path", { path })),
};

/* Types */
export type AppSettings = {
	schema_version: number,
	style: Style,
	privacy_mode: boolean,
	whisper: WhisperSettings,
	llm: LlmSettings,
	embed: EmbedSettings,
	hotkeys: HotkeySettings,
	vocabulary: string,
	per_app_styles: AppStyleOverride[],
	/**
	 *  Wrong → right substitutions injected into the cleanup prompt's
	 *  `<USER-CORRECTIONS>` block. Auto-populated by the post-paste
	 *  learning coordinator (Wave 5); manually editable in Settings.
	 */
	commonly_misheard?: MisheardReplacement[],
	/**
	 *  Pull the focused window's OCR contents into the cleanup prompt
	 *  as supporting context (Wave 5). Off by default; opt-in. Honors
	 *  `privacy_mode` — when privacy is on, OCR is skipped regardless
	 *  of this flag.
	 */
	cleanup_window_ocr?: boolean,
	/**
	 *  Watch the focused field after a paste; if the user makes a
	 *  small single-word edit (Levenshtein ≤ 3), append the
	 *  `(original, edited)` pair to `commonly_misheard` so the cleanup
	 *  prompt's `<USER-CORRECTIONS>` block applies it next time. Off
	 *  by default — auto-edits a settings field, which is the kind
	 *  of thing that needs explicit consent.
	 */
	auto_learn_corrections?: boolean,
};

export type AppStyleOverride = {
	app_id: string,
	style: Style,
};

/**
 *  Crate-wide error. Adjacently-tagged enum so the FE can pattern-match
 *  on `kind` while specta-serde stays happy (newtype variants like
 *  `AudioCapture(String)` can't coexist with an internally-tagged enum
 *  because the payload can't be merged with the tag at the same level).
 */
export type BoothError = { kind: "audio-capture"; message: string } | { kind: "transcription"; message: string } | { kind: "formatting"; message: string } | { kind: "injection"; message: string } | { kind: "internal"; message: string };

export type DictateResult = {
	raw: string,
	formatted: string,
	duration_ms: number,
};

export type EmbedSettings = {
	enabled: boolean,
	endpoint: string,
	model: string,
	api_key: string | null,
};

// One persisted dictation utterance.
export type HistoryEntry = {
	id: number,
	captured_at: string,
	raw: string,
	formatted: string,
	style: Style,
	app_exe: string | null,
	window_title: string | null,
	duration_ms: number,
	llm_ms: number,
	has_embedding: boolean,
};

export type HistoryPasteResult = {
	id: number,
	len: number,
};

export type HistoryStats = {
	total_entries: number,
	embedded_entries: number,
	db_path: string,
	embed_endpoint: string | null,
	embed_model: string | null,
};

export type HotkeySettings = {
	ptt: string,
	toggle: string,
	quick_paste: string,
};

export type LlmSettings = {
	enabled: boolean,
	endpoint: string,
	model: string,
	api_key: string | null,
};

/**
 *  1-token "are you there" probe against the configured LLM endpoint.
 *  Returns latency on success; bubbles up the error string on failure so
 *  the UI can render either case inline. Uses the user's current settings,
 *  not env vars — so it tests what the user sees in the panel, not what
 *  the binary launched with.
 */
export type LlmTestResult = {
	ok: boolean,
	latency_ms: number,
	error: string | null,
};

export type MacPermissionPane = "microphone" | "accessibility" | "input_monitoring" | 
/**
 *  Required for the Wave 5 focused-window OCR capture path. The
 *  runtime call site is still a stub on every platform — see
 *  `docs/waves/wave-5-context-aware-cleanup.md` — but exposing the
 *  pane lets users pre-grant the permission so the first OCR
 *  capture after wiring doesn't fail with a denied prompt.
 */
"screen_recording";

/**
 *  Wrong → right substitution recorded by the user (manually edited in
 *  Settings) or by the post-paste learning coordinator (auto-derived
 *  from edits the user makes after a paste). The cleanup prompt
 *  honors these as authoritative spellings.
 */
export type MisheardReplacement = {
	wrong: string,
	right: string,
};

export type ModelOption = {
	value: string,
	label: string,
	detail: string,
	file: string | null,
	/**
	 *  Whether this option is selectable. `false` for engines we list in
	 *  the picker as a roadmap signal but haven't wired the inference for
	 *  yet (e.g. Parakeet TDT until the sherpa-onnx pivot in Wave 5+).
	 *  FE disables the corresponding `<option>` element.
	 */
	available?: boolean,
};

export type SearchResult = {
	entry: HistoryEntry,
	score: number,
	// "lexical" | "semantic" | "both"
	source: string,
};

export type SettingsOptions = {
	whisper_models: ModelOption[],
	llm_models: ModelOption[],
	embed_models: ModelOption[],
};

export type SettingsPatch = {
	style?: Style | null,
	privacy_mode?: boolean | null,
	whisper?: WhisperSettings | null,
	llm?: LlmSettings | null,
	embed?: EmbedSettings | null,
	hotkeys?: HotkeySettings | null,
	vocabulary?: string | null,
	per_app_styles?: AppStyleOverride[] | null,
	commonly_misheard?: MisheardReplacement[] | null,
	cleanup_window_ocr?: boolean | null,
	auto_learn_corrections?: boolean | null,
};

export type Style = "raw" | "formal" | "casual" | "excited" | "very-casual" | 
/**
 *  Star-Trek-style log entry. Computed stardate prefix + formal
 *  24th-century rewrite. See ROADMAP § Phase 2 / Style presets.
 */
"captains-log";

export type WhisperDownloadResult = {
	model: string,
	file: string,
	path: string,
	already_present: boolean,
};

export type WhisperSettings = {
	model: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

